### ISSUE TITLE
NullPointerException on SdkContext.java

### ISSUE THREAD

**Issue by ominfowave** [InMobi/sdk-sample-code-android#14]
I have seen crash on 
```
SdkContext.java line 2148 
com.inmobi.commons.a.a.e
```
 crash report is attached below
```
Fatal Exception: java.lang.NullPointerException
       at android.webkit.WebSettingsClassic.getDefaultUserAgentForLocale(WebSettingsClassic.java:457)
       at android.webkit.WebViewClassic$Factory.getDefaultUserAgent(WebViewClassic.java:1503)
       at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1280)
       at com.inmobi.commons.a.a.e(SdkContext.java:2148)
       at com.inmobi.ads.AdUnit$6.run(AdUnit.java:1425)
       at java.lang.Thread.run(Thread.java:838)
```

all crash is reported on only `TCT` device with Android version `4.2.2`
device model

> ALCATEL ONE TOUCH 7040A
> ALCATEL ONE TOUCH 7047D
> ALCATEL ONE TOUCH 7041X

**Comment by SwagatoMondal** [comment]
This has been fixed. Please close the issue.
