### ISSUE TITLE
NullPointerException at DeviceInfo.java:66

### ISSUE THREAD

**Issue by mjurkus** [InMobi/sdk-sample-code-android#31]
__SDK version:__ 7.2.1
  
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkCapabilities.hasTransport(int)' on a null object reference
       at com.inmobi.commons.core.utilities.b.b.b(DeviceInfo.java:66)
       at com.inmobi.commons.core.utilities.b.b.a(DeviceInfo.java:113)
       at com.inmobi.commons.core.b.d.a(EventProcessor.java:129)
       at com.inmobi.commons.core.b.d.a(EventProcessor.java:1084)
       at com.inmobi.b.a.a(TRCComponent.java:9142)
       at com.inmobi.b.a$1.run(TRCComponent.java:110)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:784)
```

Let me know if you need any more details.

**Comment by lakshya21** [comment]
Hey @mjurkus, thanks for reporting the issue. 
Above issue is fixed in SDK version 7.2.2, you can go ahead and update your app with latest sdk version.
