### ISSUE TITLE
AndroidRuntimeException

### ISSUE THREAD

**Issue by Armen101** [InMobi/sdk-sample-code-android#36]
Fatal Exception: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:371)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
       at android.webkit.WebView.getFactory(WebView.java:2569)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2564)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2629)
       at android.view.View.<init>(View.java:4043)
       at android.view.View.<init>(View.java:4170)
       at android.view.ViewGroup.<init>(ViewGroup.java:603)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
       at android.webkit.WebView.<init>(WebView.java:679)
       at android.webkit.WebView.<init>(WebView.java:624)
       at android.webkit.WebView.<init>(WebView.java:607)
       at android.webkit.WebView.<init>(WebView.java:594)
       at android.webkit.WebView.<init>(WebView.java:584)
       at com.inmobi.ads.containers.RenderView.<init>(RenderView.java:334)
       at com.inmobi.ads.a.a.f(AdUnit.java:50583)
       at com.inmobi.ads.a.a$9.run(AdUnit.java:1724)
       at android.os.Handler.handleCallback(Handler.java:836)

**Comment by SwagatoMondal** [comment]
Hi @Armen101 there's nothing the SDK can do to handle this scenario where WebView is missing at that moment. Ideally this can happen only when the WebView is updating in a device, and this issue has been reported on Google. The other possible scenario being the WebView package is missing in the device, which is highly unlikely.
