### ISSUE TITLE
NullPointerException at GifMovieObject.java:70

### ISSUE THREAD

**Issue by 1105nam** [InMobi/sdk-sample-code-android#68]
Since the initial outbreak on August 26, 2020, a number of disorders have occurred in the last week.

**OS version**: Android 4 ~ 8.1.0
**SDK version**: 7.3.0

    Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Movie.width()' on a null object reference
       at com.inmobi.ads.u.b(GifMovieObject.java:70)
       at com.inmobi.ads.GifView.onMeasure(GifView.java:153)
       at android.view.View.measure(View.java:19147)
       at android.view.ViewGroup.measureChild(ViewGroup.java:6071)
       at android.view.ViewGroup.measureChildren(ViewGroup.java:6041)
       at com.inmobi.ads.NativeContainerLayout.onMeasure(NativeContainerLayout.java:20)
       at android.view.View.measure(View.java:19147)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:825)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:511)
       at com.this.is.my.app.NativeRatioRelativeLayout.onMeasure(NativeRatioRelativeLayout.java:31)
       at android.view.View.measure(View.java:19147)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:825)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:511)
       at android.view.View.measure(View.java:19147)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:825)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:511)
       at android.view.View.measure(View.java:19147)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9384)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1653)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:640)
       at com.this.is.my.app.MyAppChatActivity$initChatRecyclerView$layoutManager$1.onLayoutChildren(MyAppChatActivity.kt:937)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2728)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2552)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2255)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6708)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
       at android.view.Choreographer.doCallbacks(Choreographer.java:696)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

Let me know if you need any more details.

**Comment by im-lakshya** [comment]
Hi @1105nam 
Thanks for reporting this issue, and it seems that you're using very old version of InMobi SDK. We've iterated over lot of things since 7.3.0 and made the SDK more lighter and stable including this crash fix.

Can you update the InMobi SDK version to our latest version 9.0.9?

**Comment by 1105nam** [comment]
@im-lakshya Thanks for your kind response.  Let's try it.

**Comment by RajSuvariya-InMobi** [comment]
@1105nam Please confirm if the issue is resolved.

**Comment by 1105nam** [comment]
I use mopub, but it doesn't support inMobi anymore. So I did't try unavoidable. I don't know if it was resolved.

**Comment by RajSuvariya-InMobi** [comment]
You can check out our documentation for how to integrate InMobi with MoPub mediation https://support.inmobi.com/monetize/mediation-guidelines/mopub/android-mopub-guidelines
