### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by NingSo** [InMobi/sdk-sample-code-android#7]
java.lang.ClassCastException: com.inmobi.ads.ap cannot be cast to com.inmobi.rendering.b
	at com.inmobi.ads.bb.handleMessage(SourceFile:31)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5476)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

The version I'm using is 6.2.0, and does the later version fix this problem?. No updates were seen in the changedlog.

**Comment by SwagatoMondal** [comment]
Should have been fixed in the latest version, if not you can report again.
